### ISSUE TITLE
Sometimes CI build crashes with ObjectDisposedException

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/xoom-net-common#59]
This issue has to be investigated. Some examples:

```
04/30/2020 09:35:52.196 [21] vlingo-net/actors[Debug]: DeadLetter[Actor[type=ConsoleLoggerActor address=Address[Id=11, Name=(none)]].Close()]
856The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
857   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
858   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
859   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
860   at Vlingo.Common.Scheduler.SchedulerTask`1.Run()
861   at Vlingo.Common.Scheduler.SchedulerTask`1.Tick(Object state)
862   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
863   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
864--- End of stack trace from previous location where exception was thrown ---
865   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
866   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
867   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
868   at System.Threading.TimerQueue.FireNextTimers()
869   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

**Comment by tjaskula** [comment]
Didn't see that in a while so I'm closing it
